plugins {
    id 'java'
    id 'fabric-loom' version '1.10-SNAPSHOT'
    id "com.modrinth.minotaur" version "2.+"
}

base {
    archivesName = "$archives_name-$project.name"
}

repositories {
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
}

configurations {
    fatJar {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    minecraft "com.mojang:minecraft:$minecraft_version"
    mappings loom.officialMojangMappings()

    fatJar implementation(files(project(':common').tasks.jar))
    modImplementation "net.fabricmc:fabric-loader:$fabric_loader_version"
    modImplementation "net.fabricmc.fabric-api:fabric-api:$fabric_api_version"
    modImplementation "com.terraformersmc:modmenu:$modmenu_version"
}

processResources {
    from project(':common').tasks.processResources

    replaceProperties.compute('authors', (key, val) ->
        (val as String).split(',').collect(str -> '"' + str.trim() + '"'))

    replaceProperties['fabric_loader_version'] = fabric_loader_version

    inputs.properties replaceProperties

    filesMatching('fabric.mod.json') {
        expand replaceProperties
    }
}

remapJar.enabled = false

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from {
        configurations.fatJar.collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = "deermod"

    versionName = "Deer Mod $mod_version+$minecraft_version"
    versionNumber = "$mod_version+$minecraft_version"

    uploadFile = jar

    versionType = "release"
    loaders = ["fabric"]

    gameVersions = [minecraft_version]
    changelog = "- Added a painting of the LUVDEER!"
}