plugins {
    id 'java'
}

tasks.named('wrapper', Wrapper) {
    distributionType = Wrapper.DistributionType.ALL
}

allprojects {
    group = maven_group
    version = "$mod_version+$minecraft_version"
}

subprojects {
    java {
        sourceCompatibility = JavaVersion.toVersion(java_version)
        targetCompatibility = JavaVersion.toVersion(java_version)
    }

    ext {
        replaceProperties  = [
                'id': mod_id,
                'name': mod_name,
                'version': project.version,
                'license': mod_license,
                'authors': mod_authors,
                'description': mod_description,
                'icon': mod_icon_path,
                'minecraft_version': minecraft_version
        ]
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = java_version as int
    }
}
