# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = true
fabric.loom.multiProjectOptimisation=true
org.gradle.caching=true

# Mod properties
mod_id = deermod
mod_name = Deer Mod
mod_version = 0.6.0
mod_license = GPL-3.0-or-later
mod_authors = ArisuwuMei
mod_description = This mod adds deers to the game!
mod_icon_path = assets/deermod/icon.png
maven_group = mei.arisuwu.deermod
archives_name = deermod

# Minecraft properties
minecraft_version = 1.21.6

# Dependencies
java_version = 21
modmenu_version=14.0.0-rc.2

fabric_loader_version = 0.16.13
fabric_api_version = 0.127.0+1.21.6
neoforge_version = 21.6.5-beta

parchment_mappings_version = 1.21.5:2025.04.19
