# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = true
fabric.loom.multiProjectOptimisation=true
org.gradle.caching=true

# Mod properties
mod_id = deermod
mod_name = Deer Mod
mod_version = 0.6.0
mod_license = GPL-3.0-or-later
mod_authors = ArisuwuMei
mod_description = This mod adds deers to the game!
mod_icon_path = assets/deermod/icon.png
maven_group = mei.arisuwu.deermod
archives_name = deermod

# Minecraft properties
minecraft_version = 26.1-snapshot-10
minecraft_lowest_version = 26.1-snapshot-3

# Dependencies
java_version = 25
modmenu_version=14.0.0-rc.2

fabric_loom_version = 1.15.4
fabric_loader_version = 0.18.4
fabric_api_version = 0.143.7+26.1
neoforge_version = 26.1.0.0-alpha.12+snapshot-7
