plugins {
    id 'java'
    id 'net.neoforged.gradle.userdev' version '7.0.184'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

base {
    archivesName = "$archives_name-$project.name"
}

configurations {
    fatJar {
        canBeResolved = true
        canBeConsumed = false
    }
}

repositories {
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
}

dependencies {
    implementation "net.neoforged:neoforge:$neoforge_version"

    fatJar implementation(files(project(':common').tasks.jar))
}

processResources {
    from project(':common').tasks.processResources

    replaceProperties['neoforge_version_range'] = neoforge_version.substring(
        0, neoforge_version.findIndexValues {it == "."}.get(1) as int
    )

    inputs.properties replaceProperties

    filesMatching('META-INF/neoforge.mods.toml') {
        expand replaceProperties
    }
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from {
        configurations.fatJar.collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }
}

runs {
    configureEach {
        modSource project.sourceSets.main
    }
}
